### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed

### ISSUE THREAD

**Issue by CaioHAndradeLima** [mxn21/FlowingDrawer#65]
java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed

cellphone: NEXUS 5X API 28 Android 9

```
java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
        at android.graphics.Canvas.clipPath(Canvas.java:1007)
        at com.mxn.soul.flowingdrawer_core.FlowingMenuLayout.dispatchDraw(FlowingMenuLayout.java:109)
        at android.view.View.draw(View.java:20210)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at com.mxn.soul.flowingdrawer_core.BuildLayerFrameLayout.dispatchDraw(BuildLayerFrameLayout.java:81)
        at android.view.View.draw(View.java:20210)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at com.mxn.soul.flowingdrawer_core.ElasticDrawer.dispatchDraw(ElasticDrawer.java:775)
        at android.view.View.draw(View.java:20210)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20210)
        at com.android.internal.policy.DecorView.draw(DecorView.java:780)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3311)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3115)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2484)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at `com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
````

**Comment by PikselNsk** [comment]
Xperia XZ1
java.lang.IllegalArgumentException: 
  at android.graphics.Canvas.checkValidClipOp (Canvas.java:779)
  at android.graphics.Canvas.clipPath (Canvas.java:1007)
  at com.mxn.soul.flowingdrawer_core.FlowingMenuLayout.dispatchDraw (FlowingMenuLayout.java)
  at android.view.View.draw (View.java:20229)
  at android.view.View.updateDisplayListIfDirty (View.java:19101)
  at android.view.View.draw (View.java:19954)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4333)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
  at com.mxn.soul.flowingdrawer_core.BuildLayerFrameLayout.dispatchDraw (BuildLayerFrameLayout.java)
  at android.view.View.draw (View.java:20229)
  at android.view.View.updateDisplayListIfDirty (View.java:19101)
  at android.view.View.draw (View.java:19954)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4333)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
  at com.mxn.soul.flowingdrawer_core.ElasticDrawer.dispatchDraw (ElasticDrawer.java)
  at android.view.View.draw (View.java:20229)
  at android.view.View.updateDisplayListIfDirty (View.java:19101)
  at android.view.View.draw (View.java:19954)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4333)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
  at android.view.View.updateDisplayListIfDirty (View.java:19092)
  at android.view.View.draw (View.java:19954)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4333)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
  at android.view.View.updateDisplayListIfDirty (View.java:19092)
  at android.view.View.draw (View.java:19954)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4333)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
  at android.view.View.updateDisplayListIfDirty (View.java:19092)
  at android.view.View.draw (View.java:19954)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4333)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
  at android.view.View.updateDisplayListIfDirty (View.java:19092)
  at android.view.View.draw (View.java:19954)
  at android.view.ViewGroup.drawChild (ViewGroup.java:4333)
  at android.view.ViewGroup.dispatchDraw (ViewGroup.java:4112)
  at android.view.View.draw (View.java:20229)
  at com.android.internal.policy.DecorView.draw (DecorView.java:792)
  at android.view.View.updateDisplayListIfDirty (View.java:19101)
  at android.view.ThreadedRenderer.updateViewTreeDisplayList (ThreadedRenderer.java:686)
  at android.view.ThreadedRenderer.updateRootDisplayList (ThreadedRenderer.java:692)
  at android.view.ThreadedRenderer.draw (ThreadedRenderer.java:801)
  at android.view.ViewRootImpl.draw (ViewRootImpl.java:3332)
  at android.view.ViewRootImpl.performDraw (ViewRootImpl.java:3129)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2498)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1473)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:7215)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1004)
  at android.view.Choreographer.doCallbacks (Choreographer.java:816)
  at android.view.Choreographer.doFrame (Choreographer.java:751)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:990)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:280)
  at android.app.ActivityThread.main (ActivityThread.java:6710)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)

**Comment by jansvanda** [comment]
am getting the same.... HAAALPP

**Comment by jansvanda** [comment]
Check this out https://github.com/jansvanda/FlowingDrawer/commit/d5b37b86a43a683b93ad1845e3785a769a45fbe2

**Comment by PikselNsk** [comment]
Hello! What happened, I didn't understand any of your letter...

Best regards, Max



чт, 7 февр. 2019 г. в 23:12, Jan Švanda <notifications@github.com>:

**Comment by mxn21** [comment]
I have solved this problem with this commit ：https://github.com/mxn21/FlowingDrawer/commit/e647498f8b5c1639bd5aecb871d408e7ddc9a7fa
Please use the latest version 2.1.0
