### ISSUE TITLE
code is clean but app crash when running

### ISSUE THREAD

**Issue by sirajkrm** [mxn21/FlowingDrawer#68]
Hi,
I have implemented the project on android studio (v 3.4) with gradle 3.4.0 and SDK Android Pie
the code is clear and the build is clean,
but when running the app into AVD - Pixel 2 API 28, it crashs
here's the logcat :

`2019-05-02 07:56:23.564 16433-16433/com.mxn.soul.flowingdrawer D/AndroidRuntime: Shutting down VM
2019-05-02 07:56:23.567 16433-16433/com.mxn.soul.flowingdrawer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mxn.soul.flowingdrawer, PID: 16433
    java.lang.IllegalArgumentException: Target must not be null.
        at com.squareup.picasso.RequestCreator.into(RequestCreator.java:607)
        at com.squareup.picasso.RequestCreator.into(RequestCreator.java:590)
        at com.mxn.soul.flowingdrawer.MenuListFragment.setupHeader(MenuListFragment.java:58)
        at com.mxn.soul.flowingdrawer.MenuListFragment.onCreateView(MenuListFragment.java:45)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-05-02 07:56:23.637 16433-16433/com.mxn.soul.flowingdrawer I/Process: Sending signal. PID: 16433 SIG: 9`

![image](https://user-images.githubusercontent.com/22516813/57075868-109bbb80-6cb6-11e9-8a6d-686eddec74b8.png)

could you please see if you can fix the issue ?
much appreciation!

**Comment by mxn21** [comment]
Does this happen on other SDK version? 
If it doesn't happen on android 7,  please check again with the latest version: 1.2.1
